### ISSUE TITLE
Question: How to set response headers?

### ISSUE THREAD

**Issue by Slava** [floatinghotpot/cordova-httpd#1]
Hey there,

is there an example how to set arbitrary response headers (CORS for example) for different file depending on the request url?

**Comment by DanielDornhardt** [comment]
@Slava : Sorry for getting back to you from so long a time back, but may I ask you if you still have a solution for this on tap somehow? We're having problems with Nate Strausers' meteor-cordova-file-server - package (https://github.com/nate-strauser/meteor-cordova-file-server/issues/1), and this seems more ore less related...

Thanks and best wishes!
