### ISSUE TITLE
change root folder

### ISSUE THREAD

**Issue by mohamedzaher88** [floatinghotpot/cordova-httpd#10]
how can i change root folder to documents  folder in ios

**Comment by floatinghotpot** [comment]
use an absolute path starting with /

**Comment by sigmike** [comment]
Hi. I've tried many roots and URLs but I was unable to download files saved with the FileTransfer plugin.

The file I've downloaded is accessible through `file:///var/mobile/Containers/Data/Application/BD6BC607-EAFD-4965-B3D3-F42501672519/Documents/offline/index.html` and its `entry.fullPath` is `/offline/index.html`.

I started the server with `/` as `www_root` but I can't access it from `http://127.0.0.1:8080/offline/index.html` nor `http://127.0.0.1:8080/Documents/offline/index.html`. It always returns a not found error.

How can I access files from the `Documents` folder? Or how can I know the real absolute path served by the server?

**Comment by floatinghotpot** [comment]
your absolute path is: ```/var/mobile/Containers/Data/Application/BD6BC607-EAFD-4965-B3D3-F42501672519/Documents/offline/index.html```

if set / as your www root, i guess you need access: http://127.0.0.1:8080/var/mobile/Containers/Data/Application/BD6BC607-EAFD-4965-B3D3-F42501672519/Documents/offline/index.html

if you want to access url: ```http://127.0.0.1:8080/offline/index.html```, you'd better set www root to: ```/var/mobile/Containers/Data/Application/BD6BC607-EAFD-4965-B3D3-F42501672519/Documents```

**Comment by sigmike** [comment]
Unfortunately it doesn't work either. After some digging I figured out I had to add `/private` at the beginning of the root. So it works now. Thanks.

I don't want to handle all these absolute paths so I patched the plugin to make the root relative to the `Documents` directory instead of the bundle's `www` directory. Would you merge a PR that would make this an option or something?

**Comment by floatinghotpot** [comment]
the plugin support both absolute path and www relative folder. 

if the path given begins with /, then it will be handled as absolute path which give developer maximal freedom.

if no /, then handled as relative path under www.
